return {
	{ "folke/neoconf.nvim", cmd = "Neoconf" },
	"folke/neodev.nvim",

	{ import = "plugins.catppuccin" },
	{ import = "plugins.comment" },
	{ import = "plugins.copilot" },
	{ import = "plugins.gitsigns-nvim" },
	{ import = "plugins.hardtime-nvim" },
	{ import = "plugins.harpoon" },
	{ import = "plugins.indent-blankline" },
	{ import = "plugins.leap" },
	{ import = "plugins.lspsaga-nvim" },
	{ import = "plugins.lualine-nvim" },
	{ import = "plugins.mason" },
	{ import = "plugins.mason-lspconfig" },
	{ import = "plugins.noice" },
	{ import = "plugins.nvim-autopairs" },
	{ import = "plugins.nvim-cmp" },
	{ import = "plugins.nvim-dap" },
	{ import = "plugins.nvim-lspconfig" },
	{ import = "plugins.nvim-tree" },
	{ import = "plugins.nvim-treesitter" },
	{ import = "plugins.nvim-ts-autotag" },
	{ import = "plugins.nvim-web-devicons" },
	{ import = "plugins.tailwind-colorizer-cmp" },
	{ import = "plugins.telescope" },
	{ import = "plugins.tmux-navigator" },
	{ import = "plugins.transparent-nvim" },
	{ import = "plugins.trouble-nvim" },
	{ import = "plugins.true-zen" },
	{ import = "plugins.vim-highlightedyank" },
	{ import = "plugins.vim-illuminate" },
	{ import = "plugins.whichkey" },

	{ import = "plugins.opencode" },
}
